### PR TITLE
Weather repo

### PR DESCRIPTION
**Pull request by mlabrenz117**
Implement basic weather functionality. 

IMPORTANT: This will NOT BUILD without the keys.properties file in the root directory of the project.
This file is for any secret API keys that cannot be checked into GitHub. See Slack for a copy of the file and more information.

Includes lookup on currently_selected_lake changes and manual weather refresh.

This pull request also reorganizes the data directory.

### CODE REVIEW

**Review by lmanuelfigueroa — COMMENTED** [review]
I have been review your commit, I got weather API working with the key.properties file that you provided, but right now I get some errors about the drawables. 
Screenshot (12) and when I run the emulator the text is distorted 
Screenshot (13)

Do you experience this on your side?

**Review by lmanuelfigueroa — APPROVED** [review]
I got it to work now, for some reason even thought the file was there is wasn't recognized it, all I did was move it to another folder, build, and move it back and it successfully built. 
Screenshot (14)

**Comment by mlabrenz117** [comment]
Thanks for taking a look. I believe that was a bug in the last commit from yesterday, when I ran the code through the linter and let it try to fix things automatically it broke some stuff I didn't catch. I pushed two commits onto this pull request today that should fix the issue. Let me know if pulling the new commits doesn't fix the issue and I'll look closer.

**Comment by mlabrenz117** [comment]
@lmanuelfigueroa Is it not fetching weather data for you? Mine looks like this.
Screenshot (26)

**Comment by lmanuelfigueroa** [comment]
> Is it not fetching weather data for you? Mine looks like this.
> Screenshot (26)

No, it seems likes its not pulling anything, I'll take a look at the code and see if I can figure out why this this happening.

**Comment by mlabrenz117** [comment]
Sounds good, I'll pull a fresh copy of the git repository and test it as well.

**Comment by mlabrenz117** [comment]
@lmanuelfigueroa Pulling the develop branch and running on a fresh emulator works over here. Is there anything from volley in the Logcat tab down at the bottom of android studio? Any errors connecting to the internet should be logged there.

**Comment by lmanuelfigueroa** [comment]
There is nothing in my Logcat tab, right now I have been going through the and adding printout to see where do the values for the weather get reset to 0

**Comment by mlabrenz117** [comment]
That happens here:
https://github.com/true-soria/ShoreBuddy/blob/40af6c8b3cd206b87c5412e59eea527bed45af20/app/src/main/java/com/example/shorebuddy/data/weather/DefaultWeatherRepository.java#L20-L27

The weather constructor initializes them to zero and then when the location is changed or updateWeatherData() is called manually the fields are populated with the result of the API request.

**Pull request merged**
