### PR TITLE
Create Initial Application

### PR DESCRIPTION
**Pull request by mlabrenz117**
This pull request adds the android studio project to the repository.

### CODE REVIEW

**Review by lmanuelfigueroa — COMMENTED** [review]
I checkout the initial_app changes locally, MainActivity and ExampleUnit Test run, but ExampleInstrumented Test does not run and I get class not found error. 
Screenshot (7)

**Comment by mlabrenz117** [comment]
I just pulled a fresh copy of the repo. All tests ran to completion and the main activity worked just fine. Let me know if you need me to change anything.

**Review by lmanuelfigueroa — APPROVED** [review]
I got all the files to run now

**Comment by true-soria** [comment]
Neat.

**Pull request merged**
